### PR TITLE
added         <svg xmlns="http://w3.org/2000/svg" viewBox="0 0 100 100">

### PR DESCRIPTION
**Pull request by olavea**
<text y=".9em" font-size="90">💩</text>
</svg>
#29

### CODE REVIEW

**Comment by olavea** [comment]
<link rel="icon"
        href="data:image/svg+xml,
        <svg xmlns=%22http://w3.org/2000/svg%22 viewBox=%220 0 100 100%22>
        <text y=%22.9em%22 font-size=%2290%22>💩</text>
        </svg>" />

**Comment by olavea** [comment]
it doesn't seem to work

**Comment by raae** [comment]
It might be because of all the line breaks, I think it needs to be on one line.

**Comment by olavea** [comment]
Yess! @raae I was TOTALLY because of all the line breaks.
It WOOORKS 🎊 
silly3-new_icon-#29-8

**Comment by raae** [comment]
Great!

You want this as the favicon? Or were you just testing @olavea?

**Comment by raae** [comment]
Also you need to add it to the `{MarkdownRemark.parent__(File)__name}.js` as well. This is where I would probably create a component you can add to both `{MarkdownRemark.parent__(File)__name}.js` and `index.js` so you do not need to change both places every time you want to make a change @olavea.

**Comment by olavea** [comment]
I promise to "create a component I can add to both {MarkdownRemark.parent__(File)__name}.js and index.js so I do not need to change both places every time I want to make a change" @raae

**Comment by raae** [comment]
This is a good tutorial: https://www.gatsbyjs.com/docs/add-seo-component/

**Pull request merged**
